name: Deploy Xcard-Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NEW }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NEW }}
      AWS_REGION: ${{ secrets.AWS_REGION_NEW }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_NEW }}
      ECR_REPOSITORY: xcard
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NEW }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NEW }}
      AWS_REGION: ${{ secrets.AWS_REGION_NEW }}
      EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP_NEW }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY_NEW }}

    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NEW }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NEW }}
          AWS_REGION: ${{ secrets.AWS_REGION_NEW }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_INSTANCE_IP }}
          username: ec2-user
          key: ${{ env.EC2_PRIVATE_KEY }}
          script: |
            # Update system and install Docker if not installed
            sudo yum update -y
            sudo yum install -y docker aws-cli
            sudo systemctl start docker
            sudo systemctl enable docker

            # Ensure AWS CLI is installed
            if ! command -v aws &> /dev/null; then
              sudo yum install -y aws-cli
            fi

            # Login to Amazon ECR with AWS credentials
            export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION=${{ env.AWS_REGION }}
            aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            # Pull the latest Docker image
            sudo docker pull ${{ steps.login-ecr.outputs.registry }}/hef:latest

            # Stop and remove the existing container if running
            sudo docker stop XCARD_BACKEND || true
            sudo docker rm XCARD_BACKEND || true

            # Check if the .env.production file exists
            if [ ! -f /home/ec2-user/xcard/.env/.env.production ]; then
              echo ".env.production file is missing."
              exit 1
            fi

            # Run the new container with the .env.production file
            sudo docker run -d \
              -p 8000:8000 \
              --name XCARD_BACKEND \
              --env-file /home/ec2-user/hef/.env/.env.production \
              ${{ steps.login-ecr.outputs.registry }}/hef:latest
